version: 2
jobs:
  test:
    working_directory: ~/likecoin-store
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: likecoin-store-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm config set unsafe-perm true && npm install
      - run:
          name: Lint Test
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Server Test
          command: npm start
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://localhost:3000/
      - save_cache:
          key: likecoin-store-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  unit_test:
    working_directory: ~/likecoin-store
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: likecoin-store-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm config set unsafe-perm true && npm install
      - run:
          name: Unit Test Preparation
          command: |
            cp server/util/firebase.js server/util/firebase.js.bak
            cp server/util/ses.js server/util/ses.js.bak
            cp test/stub/server/util/firebase.js server/util/firebase.js
            cp test/stub/server/util/ses.js server/util/ses.js
      - run:
          name: Build
          command: npm run build_testnet
      - run:
          name: Unit Test Server
          command: IS_TESTNET=TRUE npm start
          background: true
      - run:
          name: Curl Unit Test Server
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://localhost:3000/
      - run:
          name: Unit Test (Express)
          command: npm run test:express
      - run:
          name: Unit Test (Nuxt)
          command: npm run test:nuxt
      - save_cache:
          key: likecoin-store-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy_rinkeby:
    working_directory: ~/likecoin-store
    docker:
      - image: lakoo/node-gcloud-docker
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - TERM: dumb
      - GOOGLE_APPLICATION_CREDENTIALS: /tmp/account-auth.json
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > /account-auth.json
            gcloud auth activate-service-account --key-file /account-auth.json
            gcloud config set project ${PROJECT_NAME}
            gcloud --quiet config set container/cluster ${POC_CLUSTER_NAME}
            gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${POC_CLUSTER_NAME}
      - setup_docker_engine
      - run:
          name: Build image
          command: |
            gcloud docker -- pull us.gcr.io/${PROJECT_NAME}/like-store:latest || true
            docker build . -t like-store --cache-from us.gcr.io/${PROJECT_NAME}/like-store:latest --build-arg IS_TESTNET='TRUE' --build-arg INTERCOM_APPID=${TEST_INTERCOM_APPID}
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:latest
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:test-${CIRCLE_SHA1}
      - run:
          name: Push images
          command: |
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:latest
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:test-${CIRCLE_SHA1}
      - deploy:
          name: Deploy
          command: |
            kubectl patch deployment like-store-rinkeby -p '{"spec":{"template":{"spec":{"containers":[{"name":"like-store","image":"us.gcr.io/'"$PROJECT_NAME"'/like-store:test-'"$CIRCLE_SHA1"'"}]}}}}'
  deploy_mainnet:
    working_directory: ~/likecoin-store
    docker:
      - image: lakoo/node-gcloud-docker
    environment:
      - DEBIAN_FRONTEND: noninteractive
      - TERM: dumb
      - GOOGLE_APPLICATION_CREDENTIALS: /tmp/account-auth.json
    steps:
      - checkout
      - run:
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > /account-auth.json
            gcloud auth activate-service-account --key-file /account-auth.json
            gcloud config set project ${PROJECT_NAME}
            gcloud --quiet config set container/cluster ${POC_CLUSTER_NAME}
            gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${POC_CLUSTER_NAME}
      - setup_docker_engine
      - run:
          name: Build image
          command: |
            gcloud docker -- pull us.gcr.io/${PROJECT_NAME}/like-store:latest || true
            docker build . -t like-store --cache-from us.gcr.io/${PROJECT_NAME}/like-store:latest --build-arg INTERCOM_APPID=${INTERCOM_APPID} --build-arg GA_TRACKING_ID=${GA_TRACKING_ID} --build-arg GTM_ID=${GTM_ID}
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:latest
            docker tag like-store:latest us.gcr.io/${PROJECT_NAME}/like-store:main-${CIRCLE_SHA1}
      - run:
          name: Push images
          command: |
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:latest
            gcloud docker -- push us.gcr.io/${PROJECT_NAME}/like-store:main-${CIRCLE_SHA1}
      - deploy:
          name: Deploy
          command: |
            kubectl patch deployment like-store-main -p '{"spec":{"template":{"spec":{"containers":[{"name":"like-store","image":"us.gcr.io/'"$PROJECT_NAME"'/like-store:main-'"$CIRCLE_SHA1"'"}]}}}}'

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - unit_test
      - hold_deploy_rinkeby:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
          requires:
           - test
           - unit_test
      - hold_deploy_mainnet:
          type: approval
          filters:
            branches:
              only: master
          requires:
           - test
           - unit_test
      - deploy_rinkeby:
          requires:
            - hold_deploy_rinkeby
      - deploy_mainnet:
          requires:
            - hold_deploy_mainnet
